//const Stock = require('./../models/stockModel');
const yellowTaxiData = require("../resources/yellow_taxi.json");

exports.getTaxiRoutes = async (req, res) => {
  let data = jsonBuilder();
  console.log(JSON.stringify(data));

  try {
    return res.status(200).json({
      data,
    });
  } catch (e) {
    res.status(404).json({
      status: "fail",
      message: e,
    });
  }
};

getCpuInfo = () => {
  let percentage = [20, 24, 25, 20, 24, 25, 21, 26, 23, 24];
  let rnd = Math.floor(Math.random() * percentage.length);
  return percentage[rnd];
};

getMemoryInfo = () => {
  let percentage = [80, 85, 80, 78, 50, 75, 70, 65, 70];
  let rnd = Math.floor(Math.random() * percentage.length);
  return percentage[rnd];
};

getNetworkInfo = () => {
  let percentage = [2, 1, 2, 2, 1, 2, 1, 2, 1];
  let rnd = Math.floor(Math.random() * percentage.length);
  return percentage[rnd];
};

getTaxiData = () => {
  let rnd = Math.floor(Math.random() * yellowTaxiData.length);
  return yellowTaxiData[rnd];
};

getQueryInfo = () => {
  return "Bronx"
}

jsonBuilder = () => {
 return {
    edges: [
      { source: 0, target: 1 },
      { source: 1, target: 5 },
      { source: 2, target: 1 },
      { source: 4, target: 3 },
      { source: 5, target: 3 },
      { source: 6, target: 4 },
      { source: 7, target: 4 },
      { source: 8, target: 5 },
      { source: 9, target: 5 },
      { source: 10, target: 6 },
      { source: 11, target: 6 },
      { source: 12, target: 7 },
      { source: 13, target: 7 },
      { source: 14, target: 8 },
      { source: 15, target: 8 },
      { source: 16, target: 9 },
      { source: 17, target: 9 },
      { source: 18, target: 10 },
      { source: 19, target: 10 },
      { source: 20, target: 11 },
      { source: 21, target: 11 },
      { source: 22, target: 12 },
      { source: 23, target: 12 },
      { source: 24, target: 13 },
      { source: 25, target: 13 },
      { source: 26, target: 14 },
      { source: 27, target: 14 },
      { source: 28, target: 15 },
      { source: 29, target: 15 },
      { source: 30, target: 16 },
      { source: 31, target: 16 },
      { source: 32, target: 17 },
      { source: 33, target: 17 },
      { source: 34, target: 18 },
      { source: 35, target: 18 },
      { source: 36, target: 19 },
      { source: 37, target: 19 },
      { source: 38, target: 20 },
      { source: 39, target: 20 },
      { source: 40, target: 21 },
      { source: 41, target: 21 },
      { source: 42, target: 22 },
      { source: 43, target: 22 },
      { source: 44, target: 23 },
      { source: 45, target: 23 },
      { source: 46, target: 24 },
      { source: 47, target: 24 },
      { source: 48, target: 25 },
      { source: 49, target: 25 },
      { source: 50, target: 26 },
      { source: 51, target: 26 },
      { source: 52, target: 27 },
      { source: 53, target: 27 },
      { source: 54, target: 28 },
      { source: 55, target: 28 },
      { source: 56, target: 29 },
      { source: 57, target: 29 },
      { source: 58, target: 30 },
      { source: 59, target: 30 },
      { source: 60, target: 31 },
      { source: 61, target: 31 },
      { source: 62, target: 32 },
      { source: 63, target: 32 },
      { source: 64, target: 33 },
      { source: 65, target: 33 },
      { source: 66, target: 34 },
      { source: 67, target: 34 },
      { source: 68, target: 35 },
      { source: 69, target: 35 },
      { source: 70, target: 36 },
      { source: 71, target: 36 },
      { source: 72, target: 37 },
      { source: 73, target: 37 },
      { source: 74, target: 38 },
      { source: 75, target: 38 },
      { source: 76, target: 39 },
      { source: 77, target: 39 },
      { source: 78, target: 40 },
      { source: 79, target: 40 },
      { source: 80, target: 41 },
      { source: 81, target: 41 },
      { source: 82, target: 42 },
      { source: 83, target: 42 },
      { source: 84, target: 43 },
      { source: 85, target: 43 },
      { source: 86, target: 44 },
      { source: 87, target: 44 },
      { source: 88, target: 45 },
      { source: 89, target: 45 },
      { source: 90, target: 46 },
      { source: 91, target: 46 },
      { source: 92, target: 47 },
      { source: 93, target: 47 },
      { source: 94, target: 48 },
      { source: 95, target: 48 },
      { source: 96, target: 49 },
      { source: 97, target: 49 },
      { source: 98, target: 50 },
      { source: 99, target: 50 },
      { source: 100, target: 51 },
      { source: 101, target: 51 },
      { source: 102, target: 52 },
      { source: 103, target: 52 },
      { source: 104, target: 53 },
      { source: 105, target: 53 },
      { source: 106, target: 54 },
      { source: 107, target: 54 },
      { source: 108, target: 55 },
      { source: 109, target: 55 },
      { source: 110, target: 56 },
      { source: 111, target: 56 },
      { source: 112, target: 57 },
      { source: 113, target: 57 },
      { source: 114, target: 58 },
      { source: 115, target: 58 },
      { source: 116, target: 59 },
      { source: 117, target: 59 },
      { source: 118, target: 60 },
      { source: 119, target: 60 },
    ],
    nodes: [
      {
        available_resources: 65535,
        id: 0,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 1,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 2,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 3,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 4,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 5,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 6,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 7,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 8,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 9,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 10,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 11,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 12,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 13,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 14,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 15,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 16,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 17,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 18,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 19,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 20,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 21,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 22,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 23,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 24,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 25,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 26,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 27,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 28,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 29,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 30,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 31,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 32,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 33,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 34,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 35,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 36,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 37,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 38,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 39,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 40,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 41,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 42,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 43,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 44,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 45,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 46,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 47,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 48,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 49,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 50,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 51,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 52,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 53,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 54,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 55,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 56,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 57,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 58,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 59,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 60,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 61,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 62,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 63,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 64,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 65,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 66,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 67,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 68,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 69,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 70,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 71,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 72,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 73,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 74,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 75,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 76,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 77,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 78,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 79,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 80,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 81,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 82,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 83,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 84,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 85,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 86,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 87,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 88,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 89,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 90,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 91,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 92,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 93,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 94,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 95,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 96,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 97,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 98,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 99,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 100,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 101,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 102,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 103,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 104,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 105,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 106,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 107,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 108,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 109,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 110,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 111,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 112,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 113,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 114,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 115,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 116,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 117,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 118,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
      {
        available_resources: 65535,
        id: 119,
        ip_address: "127.0.0.1",
        isMobile: false,
        location: null,
        query: getQueryInfo(),
        cpu: getCpuInfo(),
        memory: getMemoryInfo(),
        network: getNetworkInfo(),
        taxi_data: getTaxiData(),
      },
    ],
 }
}

// exports.getAllOptions = async (req, res) => {
//   try {
//     return res.status(200).json({
//         items: [
//           {
//             borough: "Manhattan",
//             subBoroughs: ["Manhattan_South", "Manhattan_North"],
//           },
//           {
//             borough: "Bronx",
//             subBoroughs: ["Bronx_North", "Bronx_East", "Bronx_West"],
//           },
//           {
//             borough: "Queens",
//             subBoroughs: ["Queens_Central", "Queens_North", "Queens_South"],
//           },
//           {
//             borough: "Staten_Island",
//             subBoroughs: ["Staaten_Island_North", "Staaten_Island_South"],
//           },
//           {
//             borough: "Brooklyn",
//             subBoroughs: ["Brooklyn_East", "Brooklyn_North", "Brooklyn_West"],
//           },
//         ],
//       },
//     );
//   } catch (e) {
//     res.status(404).json({
//       status: "fail",
//       message: e,
//     });
//   }
// };

// exports.getSpecificTour = async (req, res) => {
//   let district = req.params.district;
//   district = capitalizeFirstLetter(district);
//   district = capitalizeAfterUnderscore(district);

//   let filteredJson = yellowTaxiData.filter((t) => t.borough === district);
//   sendingData(filteredJson, true);
//   try {
//     return res.status(200).json({
//       message: `Sending data for ${district}. To stop this process send a PUT request to localhost:3000/api/v1/tours/`,
//     });
//   } catch (e) {
//     res.status(404).json({
//       status: "fail",
//       message: e,
//     });
//   }
// };

// exports.stopSendingData = async (req, res) => {
//   sendingData({}, false);
//   try {
//     return res.status(200).json({
//       data: {
//         Status: "stopped",
//       },
//     });
//   } catch (e) {
//     res.status(404).json({
//       status: "fail",
//       message: e,
//     });
//   }
// };

// function capitalizeFirstLetter(string) {
//   return string.charAt(0).toUpperCase() + string.slice(1);
// }

// function capitalizeAfterUnderscore(string) {
//   var i,
//     frags = string.split("_");
//   for (i = 0; i < frags.length; i++) {
//     frags[i] = frags[i].charAt(0).toUpperCase() + frags[i].slice(1);
//     console.log(frags[i]);
//   }
//   frags[0] = frags[0] + "_";
//   console.log(frags[0]);
//   frags = frags[0] + frags[1];
//   console.log(frags);
//   return frags;
// }
